const REMOTE_API_URL = process.env.REACT_APP_API_URL;
const USER_IMAGE_URL = process.env.REACT_APP_USER_IMAGE_URL;

const APP_ENV = {
    REMOTE_API_URL: REMOTE_API_URL,
    USER_IMAGE_URL: USER_IMAGE_URL
};

export default APP_ENV;